import logging

logger = logging.getLogger(__name__)
MIN_WAIT_TIME = 3
TRAIN_DIRECTION_CHANGE_TIME = 5
MIN_DISTANCE_BETWEEN_TRAINS_METERS = 10000
ACCEPTED_DELAY_PER_LINE_PER_DAY_MIN = 10
MAX_PASSENGERS_PER_H = 100
TRAIN_BREAKDOWN_TIMESLOT = [240, 1200]
